In [1]:
import pandas as pd

In [2]:
data_path = "D:/Sculptsoft/business-mention-resolution-platform/data/raw_data/yelp_academic_dataset_review.json"


chunks = pd.read_json(data_path, lines=True, chunksize=100000)

In [3]:
df = next(chunks)

In [4]:
print(df.sample(1))

                    review_id                 user_id             business_id  \
20900  Ycu0se8S0jsHVF9p4Nl_ww  IsfqByg7NeyJKFCSudsmfg  TCHh4RIrvp7h2BucXt1kvA

       stars  useful  funny  cool  \
20900      1       0      0     0

                                                    text                date
20900  Just went here in October and there was no air... 2017-10-12 02:31:19

In [11]:
df.sample(2)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
32714,11hLZSrWtG7yf1uupprQmw,Q9RltWJdfayzRArINKlE1w,X2D42cGnqxadT_jbNJxHsg,5,0,0,0,"As others have said, these guys are great! We...",2014-12-03 03:19:39
48693,z96b9f1cSsFNYOcoRmDFoQ,k5HKFBJr7nsRox9p2ZIF8g,3uYVhF4XqaZfKZg1pnLA2w,4,0,0,0,Home away from home...I seem to be here all th...,2018-07-20 12:30:38

In [6]:
for i in df.iloc[100:150, 7]:
    print(i)

Sometimes this food is very very good.  Unfortunately it's not consistent.   Ordered something I've been getting for years and every other time it tastes incredible. It's like they have different people in the kitchen and you don't know who you will get. So 50 % of the time it's excellent.  UGH.
Been to this location twice and will never go back again!!!!

First time was mediocre, the second time was so very disappointing it beggars belief. I ordered some ribs and had to send them back because one half was warm and the other half was refrigerator cold. They came back and one side was really hot and the other side was still cold, third time it was edible. The manager came over the third time to apologize, never once offered to comp anything. I'm not the kind of guy to cause a fuss to get something comped, but to send something back three times to get it cooked properly and only get an insincere apology really pisses me off, enough for me to write this review.
After trying a few ramen places with crazy variety in their selections and stellar broth, I was not too excited about the ramen I got at Cheu.  Maybe it's a matter of taste, but personally, I was not a fan of their thick noodles, and extremely salty broth.

The service was great, and they had a nice selection of beers!  The friend I went with loved it, and has been many times.  Honestly, I'm just sorry I wasn't a bigger fan.  But I hope others try it for themselves.  I might just be an oddball out on this one.
Federal Doughnuts is a new concession at the ballpark -- who doesn't love some doughnuts and fried chicken?

Also, there is now a concession stand near 136 that is gluten-free dedicated.  They offer pizza, cheesesteaks and even brownies and cookies.
Looks like there is a second Red Kings restaurant in Chinatown and it did not disappoint! Since this place just opened yesterday, I'm not exactly sure if it's replacing the other Red Kings down the street, or if it is just a second helping of spicy, Szechuan food.

We ordered takeout and picked up the Dan Dan Noodles and a shredded Pork in Garlic sauce dish. The spice level in both dishes was perfect.  Extremely mouth-burning, but with delicious flavors that were sweet, earthy, and fresh. The portions were very generous and will make for great leftovers for us. I can't wait to try some of the other dishes and come back here for a sit-down dinner. They also have karaoke rooms upstairs, plus they are BYOB.
This is one of the busiest Chick fil A's I've seen but they always manage to be quick and have exceptional service! I seriously don't know how they can be so quick and great all the time! One of my favorite places!
Best place for salads! I go there every time I'm in town for lunch. It's fast and veggies are always fresh.
My parents and I took the Oak Alley and Laura Plantation tour on September 26th, 2015.  I forgot the name of our driver-he was very informative on our drive to the plantations.  The schedule is perfect!  We were dropped off where we had time before and after the tour for free time to walk around the properties.  They are very flexible with drop off locations on the return drive.  We got off near Jackson Square and got to enjoy the rest of the afternoon in the French Quarter.
We have been here twice for brunch and have enjoyed it immensely. Everything we have tried has been delicious, particularly the grits with scallions and sour cream. But the room is always freezing so be sure to bring a sweater!
Love this place...best hot dogs and chili dogs around...i go here as many times as i can..yum
Sweet spot in the Waterline. Came for some live music with friends on Saturday. Very cool. Best local beer in town by far. Seems like the concept is a few notches up from Fig Mountain. Definitely prefer Topa. Even cooler is that you can order incredible food from the Nook Restaurant, and walk two feet into Lama Dog which is part of the Waterline. I love it!!
Great customer service! We were a little out of their pick up area but they were very accommodating and came and got our group of 7. When we got there we realized we were billed for 8 instead of 7. I called and he refunded my money for the extra ticket in minutes!

The tour itself was SO much fun! We were laughing and smiling and our tour guide was funny! We saw lots of alligators! From babies swimming in the water to full grown ones! We saw turtles and birds too! Our tour guide had a baby alligator we could hold that he's raising until it's a little bigger since it was a late hatch that would have died because of when it was born. The ride back was fun too because we went fast and the guide did some "tricks" with the boat! I highly recommend this tour!!!
Westfall replaced our roof in April. We could not be more pleased with the entire process. Quality roof, excellent communication and excellent follow up. Very happy we chose this company to replace our roof.
Good food, reasonably priced, and nice staff. Not ideal for eating in, but since they are going for a fast food approach to vegan food, that makes a lot of sense. I know the buffalo bella is the dish that they push the hardest, but for my money the Cheesesteak is the way to go. And pro-tip: Get the sweet potato fries.
The ramen is okay, nothing spectacular. Service is okay. Good place for a quick stop but wouldn't go if there were other choices. Been here twice, will continue to go.
A menu that satisfies everyone's cravings! Clean, trendy, and delicious! I definitely recommend going early (before 9 am) as the wait tends to get longer after 9 am! But honestly, it is soooo worth the wait. You will leave there feeling so incredible satisfied!
Had the brisket sandwich with two sides and a drink for 9.99 - Great barbecue at an affordable price. Wonderful side such as potato casserole cream spinach baked beans green beans
The food and service was amazing! I only wish they had any vegetarian/vegan options. Can't wait to come back!
Great food. Terrible customer service. I've been three times and I've had two different older waitresses. Not pleasant to deal with whatsoever. The owner on the other hand is lovely.
I first heard about this place on the plane ride over from a Franklin local.  He recommended that we brave the line and try one of Nashvilles best breakfast spots.  HE WAS RIGHT.  Holly cow this place kicked butt and we didn't even have to wait in line!! We were lucky to miss the rush said our waitress.   I had this super savory corn pancake with bacon, salsa, and sour cream. So good. This place will always be a stop when I get back to the south~~~
OMG!!! I can't believe this kind of service exists!  My husband called to make an appointment for full detailing for next Sat with Michael, he called again to confirm on Fri before we head there since it's a distance from our home.  Michael said he didn't know we wanted to do full detailing thou we specifically mentioned that.  He advised us to come the following sat instead.  We agreed and we reached there at 8am on the following week.  Guess what?  Nobody is at the workshop, it's closed!  We called him and he said he is busy and will call back.. We waited for half an hour in our car and there is still no call from him.  We headed for our breakfast and came back again at 9:30am hoping to give him another chance.  Here comes Alex, his partner opening the shop at 9:30am!  1.5 hours away from our appt time and still no sight of Michael.  Alex tried calling Michael and couldn't get hold of him.  We gave up!!! What a horrendous experience!
I had numerous things happen during my move and required additional services from this office. The guys in this office are top notch and are very trustworthy. I'd say more about how they took great care of me, but they may have gone above and beyond what they should have and afraid to say too much. I would recommend this office to my mother!
We stayed at The Saint last year for a girl's trip. The lobby is lovely, they have a cool bar and restaurant that you can't help but to "ohh and ahh" over when you walk in.  All the things I'm accustomed too when I stay at a hotel anywhere...ambiance, a little sexy but not overkill! Everyone is so friendly, etc.  I'm thinking "oh shhhh this is going to be a great weekend!"  I checked in a few hours before my girl arrived because I had a ton of work i needed to do. So I set up my laptop ordered some room service and worked for about 4 hours straight. Left out to buy a bottle and get a mani/pedi.  My girl arrives...its about to be some trouble in NOLA... the two of us and no supervision...we pop out for dinner, come back in giggling as usual and we see it...a HUGH flying roach.  I'm freaked out.  I literally walk right out of the room down to the front desk.  I CANNOT!!!! They tell me they're sending a maintenance worker to handle it.  NOT GOOD ENOUGH! If there's one that's bold enough to show itself, he has other cohorts that prefer to live behind the scenes. They give us another room but tell me they can't do more until 8am.  No the room the move us too also has small spiders and other dead small bugs in the corners of the window. The TV doesn't work and one of the lamps doesn't have bulbs in it! COME ON!  At this point its about 3am and I know I'm not staying here past 8:15am. I dont want to sit my purse let alone my luggage in this hotel! I go online to my normal go to hotel, The W and book us there for the rest of the trip! 8am comes and goes no manager comes to our room. I go down and demand to see someone immediately.  This younger gentlemen comes out and apologizes.  I thank him for his apology and politely request ALL of my money back immediately.   He obliged and asked if  I would consider coming back after changes have been made! Bless his heart. NO dear!
Say you decide that you need a new door...and you only have $35.  Where do you go?  the Green Project.

Or you have a bunch of left over building supplies, random bits of lumber, some roofing materials, maybe even some paint?  Where can you bring it so it doesn't end up in a landfill?  Again, the Green Project.
Worst place I've ever visited. The bouncer was rude and he didn't have to be. This place thinks just cause your on broadway you can treat people bad and over charge.
 I'm not a tourist I live here and will never visit or recommend
Stopped in for the lunch menu with my girlfriend, place was extremely clean, food was ON POINT!  And AFFORDABLE Can't wait to go back!!
So disappointing on so many levels. Have been coming here for years - and the quality of food has fallen off a cliff. Strike one - we shared an artichoke to start - and clearly it had been prepared beforehand (eg, cold on the inside - but the flesh was cooked through)  Strike two - my wife had a Greek salad - and it clearly all came from a bag and was extremely overdressed with tasteless dressing.  Strike three - I had grilled yellowtail which was basically execrable - could not even finish it (overcooked and an inferior-frozen piece of fish - unacceptable for SB).

In short - great setting, good service - but with such horrible food - not worth the visit. This place really needs to up the quality of food - or it's going to end up just another lower State dive for the tourists.
Milktooth is the place to go if you want a good breakfast cocktail and a twist on traditional brunch. At first glance of the menu, you may think you've never heard of any of these foods for breakfast, and you may be right. I guarantee no matter what you order, you're going to enjoy it.

Milktooth is one of the most popular brunch places in Indy, which means you will typically have a wait. Trust me, it's worth the usual 30 minute wait (on weekends). To make it go by a little faster, they've got a walk up bar for their coffee drinks and pastries. Snack on one of those to give you a preview of the amazing meal you're about to have.

Their menu changes from time to time but they have a few things that stay one the menu but change ingredients. I love all of their variations on a Dutch pancake, and their raclette grilled cheese is to die for.  If you're making this a boozy breakfast, don't pass up on the michelada. And sit outside if it's warm enough!
The bar and staff are AMAZING. we got a room upgrade for have been being on our honeymoon and the view was gorgeous. But, the room was not any better than a hilton. It had rust in the tub floor, and some weird stains on the tile. But this was only in the bathroom, so i give it 4 stars! Great staff, but too much for valet so we parked a couple streets down. That was the only other con I would say.

Would recommend if you want to be literally in the working downtown area of st. louis. Lots of cool bars and restaurants on a friday night.
I took the beginning class there, and I loved it. It was perfectly paced, and though the moves weren't difficult, they really stretched me in places I didn't know existed! I even broke a small sweat! But I felt great afterwards! The studio is clean, and I like that I can buy some Beyond Organic food items there too.
Not sure why it took until now for us to find this place. We started out going to the chain lobster restaurant but wanted something more authentic. A friend recommended Lobster Haven and I checked it out online. Looked like a type of place we would eat at in Massachusetts when we visit family. We were not disappointed! Service was great, fast and very friendly. Huge selection of all of the favorites. You have to visit this place if you want authentic New England seafood. You can also purchase live lobster and fresh seafood to go and cook it yourself.
Fabulous! Best happy hour, fresh menu, Delish- drinks, if I had the time, I'd come here every day!
Men's clubs is the tits, plain and simple. All the barbers got skills enough to hook it up fresh. Been coming here for 3 years and I've never had any problems. Except for maybe that one time when this dude tried to steal my cut. Tim kept it real though and said "I can't give you the same cut as Ryan." Thanks Tim.
My husband and I come here often. We love the food here, it's always fresh and the service is great. We highly recommend this place to anyone who loves sushi & hibachi.
Oh Chickie's and Pete's, you are the perfect place to watch some sports and indulge.

No doubt this is not the best food I've ever had but, if you can get a seat, grab some beer with mussels red and crab fries, there's no way not to thoroughly enjoy this place during a game or any time you're down by the stadiums.

My favs are the crab fries, mussels red (white is overloaded with garlic that I can't always take it), the spicy pull and peel shrimp, steamers, and if the mood is right the blue crabs (it's a lot of work but tasty). This place also makes getting down and dirty with your food easy. There are sinks all over so you can rinse the mess off your hands once you're done....good touch.

To sum it up, Chickie's and Pete's is a Philadelphia institution and always a good time. I strongly suggest going at least once to enjoy the experience.

Please note: Make sure to remember two things before coming during major sporting events. 1. You'll never get a table and 2. You'll deal with a ton of drunk people. I've absolutely been one of these people before and we can get annoying unless you're in the right frame of mind. :)
Prompt and professional. On a Saturday.
Simple mirror fix, but they made it easy for me. I have used them in Charlotte and they were great then, too.
Good choice in Union Station St. Louis.  I had the Ponchartrain (server said it is same as Tilapia, though that was also on the menu, so why two names for the same fish, I have no clue).  The Ponchartrain was quite good with mushrooms and a cream sauce.  We also had the shrimp cocktail and lump crab cake appetizers....both fine, but not wonderful.  Drinks and service were perfectly acceptable.  We dined outside on the patio since the weather was nice - inside looks comfy and a bit less casual.
I stopped in for a drink yesterday and have to say the atmosphere gets an A+ from me.  Such a unique concept for the St. Pete area.  The attention to detail with the remodel was outstanding, it almost feels like you are in a Harry Potter movie or something.  There is background music that is set at a low volume so you can clearly hear your friends or not have to shout for them to hear you - perfect for the old library-esque environment. Working behind the bar were Michael and Peggy - both couldn't have been more friendly and were overall just interesting people to talk to.   I had eaten dinner already before I came so can't speak on the food but will definitely be back to try - the prices for meat/cheese trays are much better than comparable places in the area.  I would definitely recommend checking this place out...
Yes! I love this place! Maple Street Patisserie is the bomb.com! I've never been disappointed. Best blueberry muffin I've ever had in my whole entire life. Delicious breakfast and lunch spot. They also do specialty cakes so swing by during Mardi Gras and grab a king cake. Also the owner, Ziggy, is the man. He's always running around working crazy hours to make all these scrumptious baked goods. Can't beat this place :)
Really good burger. I had the Bourbon Black and Bleu. It was cooked like I wanted and very tasty.

I gave them 3 stars for the wait. We had a big party - 4 adults and 5 kids - and it took over an hour to get our food. Shouldn't have taken that long, regardless of how many people were at our table.
It seems to me that whenever we have out of towner guests, our go to place is consistently Katie's. The variety of food wonderfully prepared is 2nd to none. Reasonably priced and delicious, Katie's never disappoints. Whether you choose the grilled ersters, the shrimp and grits, the Cuban sandwich, pizza, or soup & salad you will be very pleased and have a great meal. Daily specials hi-lite local seasonal offerings that keep things fresh. The service staff are warm and friendly. On Sunday's, you will want to time your arrival before church let's out or you will have a bit of a wait. That said, you can always manage while enjoying bottomless Mimosas!
Came in after attending the Zurich Classic golf tournament. It was a warm and a bit humid so what tastier then a ice cream cone? I lucked out and found a parking space on the street. The interior is quite cute and comfy.

The selection here is crazy huge but after sampling a couple of unusual flavors I went with the scoop of cookie monster ice cream on a cone. The ice cream hit the spot and I enjoyed it BC it wasn't overly sweet.

Creole Creamery was definitely worth checking out!
I LOVE this place!  I have been coming here for a few years now.  Its a little funky, and I would never order say the escargot, for safety reasons, but when it comes to lots of Saki, great rolls, and mountains of rice and Sashimi, this is the way to go.  Young atmosphere, loud dance music, and SAKI!
We absolutely love everything we have tried here. Our favorite thus far has been the Backyard Bowl, although there are several more that we still need to try. My husband and I are always full after we each get a kids size, or split a large. The ingredients are good quality,  filling foods. For the quality of ingredients, the price is very reasonable. It can get pretty busy here, but have patience, it is worth the wait.
It's was okay service was a bit on the interesting side as the person was new. Food presentation was good though they need to either add rice or more potato salad to the gumbo. Sprite was flat but I didn't need it anyways.
This is a pretty good pancake place, but it's a little disorganized in the way it's run when it's really busy. The pancakes are pretty good but super sweet, so you have to be in there. Good price point. Serves breakfast all day so that's definitely a plus, but not anything particularly special that you couldn't get anywhere else.
Great finds and wonderful staff!

In [20]:
df.columns

Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'text', 'date'],
      dtype='str')

In [2]:
data_path = "D:/Sculptsoft/business-mention-resolution-platform/data/raw_data/yelp_academic_dataset_business.json"


chunks2 = pd.read_json(data_path, lines=True, chunksize=100000)

In [3]:
df2 = next(chunks2)

In [10]:
print(df2.sample(1))

                  business_id                 name          address   city  \
62288  PB8LPiw46BXq40AFLZqxkQ  Wolff's Apple House  81 S Pennell Rd  Media

      state postal_code   latitude  longitude  stars  review_count  is_open  \
62288    PA       19063  39.906734 -75.439729    4.5            38        1

                                              attributes  \
62288  {'BusinessParking': '{'garage': False, 'street...

                                              categories  \
62288  Food, Fruits & Veggies, Farmers Market, Grocer...

                                                   hours
62288  {'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...

In [27]:
df2.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours'],
      dtype='str')

In [13]:
df2.sample(2)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
83245,7V7cxGLM-xZ7C44-1DfvSw,Chubby crab,5717 Rising Sun Ave,Philadelphia,PA,19120,40.041642,-75.105872,2.5,9,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Fish & Chips, Burgers, Restaurants, Seafood","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
76248,UPzloPwTmQymKLht9epxbA,The Tavern at Cheval,4312 Cheval Blvd,Lutz,FL,33558,28.152595,-82.510104,4.0,9,1,"{'BusinessAcceptsCreditCards': 'True', 'BYOB':...","American (Traditional), Restaurants, Nightlife...","{'Wednesday': '17:0-20:0', 'Thursday': '17:0-2..."

In [5]:
len(df2.columns)

14

In [7]:
df2.shape

(100000, 14)