In [1]:
import pandas as pd

In [2]:
data_path = "D:/Sculptsoft/business-mention-resolution-platform/data/raw_data/yelp_academic_dataset_review.json"


chunks = pd.read_json(data_path, lines=True, chunksize=100000)

In [3]:
df = next(chunks)

In [4]:
print(df.sample(1))

                    review_id                 user_id             business_id  \
20900  Ycu0se8S0jsHVF9p4Nl_ww  IsfqByg7NeyJKFCSudsmfg  TCHh4RIrvp7h2BucXt1kvA

       stars  useful  funny  cool  \
20900      1       0      0     0

                                                    text                date
20900  Just went here in October and there was no air... 2017-10-12 02:31:19

In [11]:
df.sample(2)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
32714,11hLZSrWtG7yf1uupprQmw,Q9RltWJdfayzRArINKlE1w,X2D42cGnqxadT_jbNJxHsg,5,0,0,0,"As others have said, these guys are great! We...",2014-12-03 03:19:39
48693,z96b9f1cSsFNYOcoRmDFoQ,k5HKFBJr7nsRox9p2ZIF8g,3uYVhF4XqaZfKZg1pnLA2w,4,0,0,0,Home away from home...I seem to be here all th...,2018-07-20 12:30:38

In [13]:
for i in df.iloc[40000:40009, 7]:
    print(i)
    print()

I was unexpectedly surprised with how much I liked this place. I came here for a late dinner, just wanting something small and light since I've been eating all day. It's a pretty small and cozy place, with a few tables outside. All the tables were taken, but we were able to sit at the high tops where they made the pizzas. Best seats in the house!

They were super efficient in making the pizzas. All the ingredients looked fresh and plentiful on the pizzas themselves. The pies coming out of their wood burning oven looked amazing. I enjoyed watching them make them through the night. Looking at that, as well as the menu, I didn't want anything small anymore but wanted to try a little bit of everything.

Got the Italian Cesar salad- anchovies topped the salad so it had that saltiness in each and every bite. The pizza dough as the croutons were warm and doughy.

While waiting for our pizza, they had an extra calzone and hooked it up for free. Thanks!

Got the pepperoni and crudo pies. I love the crust of these pizzas- perfectly charred from the oven. The pepperoni was crunchy and not oily. It was like eating tiny pepperoni chips! For the crudo pie, The prosciutto was great with the buffalo mozzarella and every bite was salty and creamy.

Even though we were full, we wanted to try the nutella pie for dessert. So glad I did! The pie was again perfectly charred and the nutella and marshmallow was perfectly melted. I just wish I had milk to wash it all down.

Overall a great experience. The hip hop music playing in the background topped it all off. It wasn't too loud that you could still hear yourself carry a conversation. Will def go back next time I'm in the area.

It was a wait,but worth it I enjoy every bite

the pancake was ok

This place has gone downhill. Extremely slow service, always out of ingredients, always get the wrong order. Probably won't be back.

Excellent service, has air conditioning which is great in the south, my favorite was the chicken chicharrón "chicharrón" good location in the block is the best one!

Came here for Sunday brunch, of course the place was crowded but we didn't have to wait long to get seated. The food was delicious and our waitress was nice. However this place can get super cramped when busy and becomes hard to get around for the buffet.

The blonde girl server was very rude and disrespectful. I asked her if there were any daily special juices and she said no, while the other server told the guests at the next table that there were. Felt like she just wanted to send me away as soon as I finished my food. Her attitude in general made me feel very uncomfortable and angry. The food was ok too. The tofu platter was a little too salty.

Blah! Expensive prices aside which should be implicit by its trendy, white friendly location. The people they have working here may be the most rude and disinterested people I've every encountered in a grocery market that's supposedly 'fancy' and what have you. The kids at the registers just stare at you when you walk in, vacant expressions replete within the bunch and the more than likely whatever depleted manager they have on just ignores you and then gives you dirty looks as you leave. Go to Trader Joes, five blocks away, this place is a joke, exclusive for those willing to pay four times as much to live in a trendy neighborhood.

AMAZING. You need to make a reservation far in advance but well worth it. Service was flawless. The antipasto was crazy good, highly recommend it.

At first I thought this place was going to be boring. I went because a friend of mine likes nature so I was like, what the heck, let's go. First of all, the staff was very nice and I loved their set up. It was both indoors and out. The indoors offered more of an art set up and little shopping centers. The outdoors was very beautiful and relaxing. I took a lot of pictures because it was giving me ideas of different plants and landscape that I can do around my house. Also, the further you walk up, there was the Lilly house along with a tour. It was enormous and  gorgeous inside. I won't tell you who the Lilly family was because I don't want to ruin the tour for you guys in case you'll decide to check it out. They also had the beer garden which we didnt get a chance to check out because we had other places to be. They have their own parking lot and Cafe shops with plenty of seating areas. I would visit again just because I didn't get a chance to walk and see everything. You will spend a couple hours out there. I even seen some couples having a picnic. The amount of acres is ridiculous.

In [20]:
df.columns

Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'text', 'date'],
      dtype='str')

In [2]:
data_path = "D:/Sculptsoft/business-mention-resolution-platform/data/raw_data/yelp_academic_dataset_business.json"


chunks2 = pd.read_json(data_path, lines=True, chunksize=100000)

In [3]:
df2 = next(chunks2)

In [10]:
print(df2.sample(1))

                  business_id                 name          address   city  \
62288  PB8LPiw46BXq40AFLZqxkQ  Wolff's Apple House  81 S Pennell Rd  Media

      state postal_code   latitude  longitude  stars  review_count  is_open  \
62288    PA       19063  39.906734 -75.439729    4.5            38        1

                                              attributes  \
62288  {'BusinessParking': '{'garage': False, 'street...

                                              categories  \
62288  Food, Fruits & Veggies, Farmers Market, Grocer...

                                                   hours
62288  {'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...

In [27]:
df2.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours'],
      dtype='str')

In [13]:
df2.sample(2)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
83245,7V7cxGLM-xZ7C44-1DfvSw,Chubby crab,5717 Rising Sun Ave,Philadelphia,PA,19120,40.041642,-75.105872,2.5,9,0,"{'Ambience': '{'touristy': False, 'hipster': F...","Fish & Chips, Burgers, Restaurants, Seafood","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
76248,UPzloPwTmQymKLht9epxbA,The Tavern at Cheval,4312 Cheval Blvd,Lutz,FL,33558,28.152595,-82.510104,4.0,9,1,"{'BusinessAcceptsCreditCards': 'True', 'BYOB':...","American (Traditional), Restaurants, Nightlife...","{'Wednesday': '17:0-20:0', 'Thursday': '17:0-2..."

In [5]:
len(df2.columns)

14

In [7]:
df2.shape

(100000, 14)